export const ORDER_STATUS = {

    PENDING: "PENDING",

    CONFIRMED: "CONFIRMED",

    PROCESSING: "PROCESSING",

    SHIPPED: "SHIPPED",

    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",

    DELIVERED: "DELIVERED",

    CANCELLED: "CANCELLED",

    RETURN_REQUESTED: "RETURN_REQUESTED",

    RETURNED: "RETURNED"

};