export const PAYMENT_STATUS = {

    PENDING: "PENDING",

    SUCCESS: "SUCCESS",

    FAILED: "FAILED",

    CANCELLED: "CANCELLED",

    REFUNDED: "REFUNDED",

    PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED"

};