export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  RECEPTIONIST: "RECEPTIONIST",
  TECHNICIAN: "TECHNICIAN",
  INVENTORY: "INVENTORY",
  ACCOUNTANT: "ACCOUNTANT",
  CUSTOMER: "CUSTOMER",
};