export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  SALES:"SALES",
  TECHNICIAN: "TECHNICIAN",
  INVENTORY: "INVENTORY",
  ACCOUNTANT: "ACCOUNTANT",
  CUSTOMER: "CUSTOMER",
  IT_SUPPORT:"IT_SUPPORT",
  ADMINISTRATION_FACILITIES:"ADMINISTRATION_FACILITIES",
  HR_EXECUTIVE:"HR_EXECUTIVE",
  PROCUREMENT_TEAM:"PROCUREMENT_TEAM"


};