export const SHIPMENT_STATUS = {

    PENDING: "PENDING",

    PACKED: "PACKED",

    SHIPPED: "SHIPPED",

    IN_TRANSIT: "IN_TRANSIT",

    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",

    DELIVERED: "DELIVERED",

    RETURNED: "RETURNED",

    CANCELLED: "CANCELLED"

};

Object.freeze(SHIPMENT_STATUS);